### ISSUE TITLE
Crash reporter crashing

### ISSUE THREAD

**Issue by z16** [Windower/packages#109]
Easy to reproduce with this:
```lua
/eval print(require('ffi').cast('char*', 0)[0])
```

Example crash event log:
https://pastebin.com/7mu5jgbZ

**Comment by alphaONE2** [comment]
Found the issue, I forgot to update the escaped version of the full path when updating the dump path to match the user's settings. This meant that it would save the dump to one path and then tell launcher about a completely different path. Launcher would obviously not be able to find the dump at the path that core told it about and then because of a lack of exception handling crashed itself.
